[2024-02-22T00:10:59.341+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:10:59.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:11:00.043+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:10:59.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:11:27.938+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:11:27.879+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:11:27.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:11:29.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 30.968 seconds
[2024-02-22T00:12:23.389+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:12:23.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:12:24.530+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:12:24.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:12:37.458+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:12:37.224+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:12:37.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:12:41.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 25.340 seconds
[2024-02-22T00:13:17.771+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:13:17.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:13:17.909+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:13:17.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:13:26.392+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:13:26.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:13:26.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:13:28.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 11.446 seconds
[2024-02-22T00:13:59.959+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:14:00.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:14:00.118+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:14:00.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:14:13.559+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:14:13.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:14:13.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:14:16.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 16.568 seconds
[2024-02-22T00:14:51.777+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:14:52.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:14:52.517+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:14:52.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:15:25.302+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:15:25.215+0000] {timeout.py:68} ERROR - Process timed out, PID: 61
[2024-02-22T00:15:26.674+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:15:25.305+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs_sensor import GoogleCloudStorageObjectUpdatedSensor
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 31, in <module>
    from airflow.providers.google.cloud.hooks.gcs import GCSHook
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 47, in <module>
    from airflow.providers.google.common.hooks.base_google import GoogleBaseAsyncHook, GoogleBaseHook
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 43, in <module>
    from googleapiclient import discovery
  File "/home/airflow/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 130, in <module>
    class _BytesGenerator(BytesGenerator):
  File "/home/airflow/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 131, in _BytesGenerator
    _write_lines = BytesGenerator.write
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/upload_docs.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.1/best-practices.html#reducing-dag-complexity, PID: 61
[2024-02-22T00:15:26.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:15:37.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 46.678 seconds
[2024-02-22T00:16:17.308+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:16:19.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:16:20.379+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:16:20.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:16:52.878+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:16:52.528+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:16:52.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:16:56.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 40.682 seconds
[2024-02-22T00:17:35.706+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:17:35.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:17:36.135+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:17:36.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:17:54.542+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:17:54.313+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:17:54.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:17:56.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 21.287 seconds
[2024-02-22T00:18:32.193+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:18:32.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:18:32.295+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:18:32.285+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:18:54.531+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:18:53.915+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:18:54.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:18:57.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 26.254 seconds
[2024-02-22T00:19:32.020+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:19:32.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:19:32.357+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:19:32.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:19:42.738+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:19:42.586+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:19:42.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:19:45.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 13.366 seconds
[2024-02-22T00:20:19.824+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:20:19.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:20:19.977+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:20:19.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:20:31.938+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:20:31.743+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:20:31.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:20:36.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 16.552 seconds
[2024-02-22T00:21:08.590+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:21:08.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:21:08.684+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:21:08.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:21:36.855+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:21:36.710+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:21:36.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:21:39.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 31.230 seconds
[2024-02-22T00:22:12.909+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:22:12.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:22:12.967+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:22:12.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:22:17.865+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:22:17.795+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:22:17.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:22:19.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 7.094 seconds
[2024-02-22T00:22:50.507+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:22:50.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:22:50.547+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:22:50.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:22:52.529+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:22:52.514+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:22:52.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:22:52.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.362 seconds
[2024-02-22T00:23:23.546+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:23:23.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:23:23.575+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:23:23.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:23:26.967+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:23:26.910+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:23:26.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:23:28.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 4.552 seconds
[2024-02-22T00:23:58.976+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:23:58.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:23:58.992+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:23:58.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:24:02.053+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:24:02.015+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:24:02.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:24:02.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 3.572 seconds
[2024-02-22T00:24:44.912+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:24:44.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:24:44.974+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:24:44.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:24:46.878+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:24:46.827+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:24:46.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:24:47.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.562 seconds
[2024-02-22T00:25:18.005+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:25:18.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:25:18.019+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:25:18.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:25:21.024+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:25:20.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:25:21.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:25:23.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 5.190 seconds
[2024-02-22T00:25:55.839+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:25:55.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:25:55.852+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:25:55.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:25:58.230+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:25:58.192+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:25:58.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:26:16.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 20.416 seconds
[2024-02-22T00:26:47.751+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:26:47.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:26:47.887+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:26:47.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:26:49.075+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:26:49.066+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:26:49.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:26:49.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.983 seconds
[2024-02-22T00:27:19.725+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:27:19.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:27:19.746+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:27:19.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:27:21.809+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:27:21.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:27:21.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:27:23.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 3.522 seconds
[2024-02-22T00:27:54.381+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:27:54.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:27:54.393+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:27:54.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:27:55.706+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:27:55.690+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:27:55.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:27:56.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.662 seconds
[2024-02-22T00:28:40.608+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:28:40.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:28:40.624+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:28:40.623+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:28:51.361+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:28:50.544+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:28:51.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:28:56.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 19.505 seconds
[2024-02-22T00:29:27.654+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:29:27.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:29:27.673+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:29:27.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:29:30.442+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:29:30.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:29:30.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:29:31.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 3.593 seconds
[2024-02-22T00:30:02.332+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:02.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:30:02.338+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:30:02.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:03.847+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:30:03.792+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:30:03.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:04.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.196 seconds
[2024-02-22T00:30:05.925+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:05.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:30:05.933+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:30:05.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:06.414+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:30:06.405+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:30:06.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:09.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 3.782 seconds
[2024-02-22T00:30:40.692+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:40.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:30:40.700+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:30:40.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:41.484+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:30:41.462+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:30:41.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:30:41.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.156 seconds
[2024-02-22T00:31:05.246+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:31:05.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:31:05.255+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:31:05.253+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:31:06.880+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:31:06.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:31:06.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:31:07.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.305 seconds
[2024-02-22T00:31:44.878+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:31:44.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:31:44.884+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:31:44.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:31:45.981+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:31:45.945+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:31:45.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:31:46.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.989 seconds
[2024-02-22T00:32:18.476+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:32:18.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:32:18.485+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:32:18.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:32:20.390+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:32:20.368+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:32:20.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:32:22.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 3.975 seconds
[2024-02-22T00:32:50.334+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:32:50.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:32:50.360+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:32:50.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:32:51.668+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:32:51.637+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:32:51.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:00.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 10.154 seconds
[2024-02-22T00:33:07.594+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:07.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:33:07.603+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:33:07.601+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:08.283+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:33:08.273+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:33:08.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:10.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.483 seconds
[2024-02-22T00:33:19.002+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:19.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:33:19.006+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:33:19.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:19.751+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:33:19.738+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:33:19.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:20.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.653 seconds
[2024-02-22T00:33:50.995+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:50.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:33:50.999+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:33:50.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:51.606+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:33:51.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:33:51.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:33:51.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.832 seconds
[2024-02-22T00:34:11.534+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:11.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:34:11.551+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:34:11.549+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:11.614+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:34:11.610+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 15
    print("Remotely received value of {} for key=message".format(kwargs['dag_run'].conf['file_name'])))
                                                                                                      ^
SyntaxError: unmatched ')'
[2024-02-22T00:34:11.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:11.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.297 seconds
[2024-02-22T00:34:15.435+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:15.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:34:15.440+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:34:15.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:15.889+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:34:15.879+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:34:15.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:16.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.623 seconds
[2024-02-22T00:34:46.305+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:46.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:34:46.312+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:34:46.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:47.625+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:34:47.438+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:34:47.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:34:47.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.662 seconds
[2024-02-22T00:35:18.520+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:35:18.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:35:18.525+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:35:18.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:35:20.437+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:35:20.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:35:20.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:35:22.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 4.356 seconds
[2024-02-22T00:35:54.553+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:35:54.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:35:54.596+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:35:54.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:35:55.465+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:35:55.454+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:35:55.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:35:56.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.887 seconds
[2024-02-22T00:36:26.989+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:36:27.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:36:27.029+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:36:27.028+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:36:28.902+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:36:28.884+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:36:28.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:36:31.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 4.280 seconds
[2024-02-22T00:37:01.908+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:37:01.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:37:01.932+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:37:01.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:37:03.595+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:37:03.487+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:37:03.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:37:04.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.251 seconds
[2024-02-22T00:37:34.958+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:37:34.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:37:34.965+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:37:34.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:37:36.368+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:37:36.360+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:37:36.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:37:36.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.599 seconds
[2024-02-22T00:38:06.736+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:38:06.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:38:06.742+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:38:06.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:38:07.359+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:38:07.349+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:38:07.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:38:07.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.021 seconds
[2024-02-22T00:38:38.211+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:38:38.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:38:38.217+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:38:38.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:38:38.923+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:38:38.914+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:38:38.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:38:39.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.964 seconds
[2024-02-22T00:39:09.670+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:39:09.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:39:09.675+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:39:09.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:39:10.763+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:39:10.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:39:10.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:39:18.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 9.132 seconds
[2024-02-22T00:39:51.054+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:39:51.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:39:51.063+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:39:51.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:39:51.726+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:39:51.718+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:39:51.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:39:53.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.162 seconds
[2024-02-22T00:40:23.590+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:40:23.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:40:23.600+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:40:23.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:40:24.586+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:40:24.570+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:40:24.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:40:25.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.479 seconds
[2024-02-22T00:40:58.031+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:40:58.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:40:58.038+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:40:58.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:40:58.834+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:40:58.824+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:40:58.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:40:59.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.080 seconds
[2024-02-22T00:41:31.924+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:41:31.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:41:31.929+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:41:31.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:41:32.515+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:41:32.505+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:41:32.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:41:34.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.329 seconds
[2024-02-22T00:42:11.258+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:42:11.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:42:11.304+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:42:11.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:42:14.162+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:42:14.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:42:14.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:42:15.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 4.773 seconds
[2024-02-22T00:42:46.483+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:42:46.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:42:46.491+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:42:46.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:42:47.077+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:42:47.066+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:42:47.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:42:47.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.931 seconds
[2024-02-22T00:43:17.986+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:43:17.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:43:17.991+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:43:17.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:43:18.532+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:43:18.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:43:18.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:43:18.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.011 seconds
[2024-02-22T00:43:49.159+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:43:49.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:43:49.271+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:43:49.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:43:49.891+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:43:49.883+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:43:49.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:43:50.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.325 seconds
[2024-02-22T00:44:21.712+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:44:21.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:44:21.717+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:44:21.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:44:22.368+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:44:22.356+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:44:22.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:44:22.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.954 seconds
[2024-02-22T00:44:53.258+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:44:53.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:44:53.290+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:44:53.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:44:54.061+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:44:54.044+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:44:54.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:44:54.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.020 seconds
[2024-02-22T00:45:24.400+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:45:24.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:45:24.405+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:45:24.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:45:24.816+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:45:24.808+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:45:24.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:45:25.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.663 seconds
[2024-02-22T00:45:55.238+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:45:55.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:45:55.245+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:45:55.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:45:56.032+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:45:56.024+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:45:56.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:45:56.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.022 seconds
[2024-02-22T00:46:27.245+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:46:27.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:46:27.251+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:46:27.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:46:27.795+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:46:27.785+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:46:27.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:46:32.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 5.366 seconds
[2024-02-22T00:47:03.272+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:47:03.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:47:03.302+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:47:03.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:47:03.857+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:47:03.846+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:47:03.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:47:04.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.913 seconds
[2024-02-22T00:47:34.670+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:47:34.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:47:34.674+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:47:34.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:47:35.141+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:47:35.133+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:47:35.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:47:35.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.997 seconds
[2024-02-22T00:48:07.328+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:48:07.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:48:07.334+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:48:07.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:48:08.078+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:48:08.066+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:48:08.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:48:08.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.188 seconds
[2024-02-22T00:48:39.359+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:48:39.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:48:39.364+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:48:39.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:48:40.015+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:48:40.005+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:48:40.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:48:40.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.056 seconds
[2024-02-22T00:49:10.761+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:49:10.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:49:10.766+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:49:10.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:49:11.524+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:49:11.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:49:11.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:49:11.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.005 seconds
[2024-02-22T00:49:42.746+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:49:42.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:49:42.750+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:49:42.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:49:43.283+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:49:43.275+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:49:43.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:49:43.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.735 seconds
[2024-02-22T00:50:13.806+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:13.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:50:13.810+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:50:13.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:14.268+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:50:14.260+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:50:14.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:14.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.655 seconds
[2024-02-22T00:50:32.952+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:32.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:50:32.968+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:50:32.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:33.572+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:50:33.562+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:50:33.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:33.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.865 seconds
[2024-02-22T00:50:57.695+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:57.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:50:57.703+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:50:57.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:57.802+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:50:57.791+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:50:57.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:50:58.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.319 seconds
[2024-02-22T00:51:17.038+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:17.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:51:17.047+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:51:17.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:17.105+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:51:17.097+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.providers.google.cloud.sensors.gcs.GCSObjectUpdateSensor import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.providers.google.cloud.sensors.gcs.GCSObjectUpdateSensor'; 'airflow.providers.google.cloud.sensors.gcs' is not a package
[2024-02-22T00:51:17.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:17.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.327 seconds
[2024-02-22T00:51:20.541+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:20.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:51:20.547+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:51:20.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:20.609+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:51:20.602+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2024-02-22T00:51:20.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:20.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.239 seconds
[2024-02-22T00:51:37.074+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:37.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:51:37.081+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:51:37.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:37.142+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:51:37.135+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:51:37.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:51:40.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 3.315 seconds
[2024-02-22T00:52:10.956+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:10.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:52:10.962+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:10.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:11.007+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:10.997+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:52:11.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:11.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.246 seconds
[2024-02-22T00:52:29.863+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:29.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:52:29.869+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:29.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:29.908+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:29.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4
    from airflow.providers.google.cloud.sensors.gcs. import GoogleCloudStorageObjectUpdatedSensor
                                                     ^
SyntaxError: invalid syntax
[2024-02-22T00:52:29.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:30.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.219 seconds
[2024-02-22T00:52:33.620+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:33.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:52:33.626+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:33.625+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:33.691+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:33.684+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2024-02-22T00:52:33.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:33.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.301 seconds
[2024-02-22T00:52:40.607+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:40.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:52:40.615+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:40.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:40.651+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:40.650+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4
    from airflow.providers.google.cloud.sensors.gcs. import GoogleCloudStorageObjectUpdatedSensor
                                                     ^
SyntaxError: invalid syntax
[2024-02-22T00:52:40.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:40.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.238 seconds
[2024-02-22T00:52:42.800+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:42.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:52:42.806+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:42.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:42.935+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:52:42.923+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:52:42.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:52:43.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.359 seconds
[2024-02-22T00:53:02.821+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:02.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:02.827+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:02.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:02.888+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:02.881+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2024-02-22T00:53:02.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:03.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.244 seconds
[2024-02-22T00:53:06.740+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:06.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:06.745+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:06.745+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:06.800+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:06.793+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2024-02-22T00:53:06.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:06.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.240 seconds
[2024-02-22T00:53:13.027+0000] {processor.py:161} INFO - Started process (PID=133) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:13.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:13.034+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:13.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:13.097+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:13.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:53:13.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:13.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.281 seconds
[2024-02-22T00:53:44.431+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:44.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:44.437+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:44.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:44.471+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:44.464+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:53:44.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:44.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.311 seconds
[2024-02-22T00:53:50.127+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:50.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:50.133+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:50.132+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:50.214+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:50.207+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 6, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain'
[2024-02-22T00:53:50.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:50.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.278 seconds
[2024-02-22T00:53:56.053+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:56.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:56.057+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:56.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:56.119+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:56.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors.gcs import GoogleCloudStorageObjectUpdatedSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.gcs'
[2024-02-22T00:53:56.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:56.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.245 seconds
[2024-02-22T00:53:59.279+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:59.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:53:59.288+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:59.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:59.352+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:53:59.344+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:53:59.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:53:59.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.241 seconds
[2024-02-22T00:54:30.864+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:54:30.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:54:30.869+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:54:30.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:54:30.909+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:54:30.901+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:54:30.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:54:31.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.255 seconds
[2024-02-22T00:54:36.029+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:54:36.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:54:36.042+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:54:36.041+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:54:36.119+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:54:36.112+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:54:36.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:54:36.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.400 seconds
[2024-02-22T00:55:06.949+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:55:06.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:55:06.995+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:55:06.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:55:07.095+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:55:07.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:55:07.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:55:07.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.694 seconds
[2024-02-22T00:55:38.488+0000] {processor.py:161} INFO - Started process (PID=141) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:55:38.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:55:38.593+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:55:38.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:55:38.856+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:55:38.834+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:55:38.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:55:39.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.848 seconds
[2024-02-22T00:56:15.710+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:56:15.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:56:15.781+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:56:15.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:56:16.797+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:56:16.732+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:56:16.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:56:18.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 4.262 seconds
[2024-02-22T00:56:50.135+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:56:50.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:56:50.172+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:56:50.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:56:50.269+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:56:50.259+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:56:50.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:56:50.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.509 seconds
[2024-02-22T00:57:08.949+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:08.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:57:08.975+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:08.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:09.117+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:09.103+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:57:09.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:09.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.550 seconds
[2024-02-22T00:57:12.757+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:12.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:57:12.782+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:12.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:12.939+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:12.928+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:57:12.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:13.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.776 seconds
[2024-02-22T00:57:42.542+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:42.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:57:42.586+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:42.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:42.662+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:42.651+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4
    from  airflow.operators
                          ^
SyntaxError: invalid syntax
[2024-02-22T00:57:42.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:43.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.215 seconds
[2024-02-22T00:57:46.522+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:46.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:57:46.578+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:46.574+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:46.661+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:46.655+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 4
    from  airflow.operators.bash
                               ^
SyntaxError: invalid syntax
[2024-02-22T00:57:46.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:47.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.693 seconds
[2024-02-22T00:57:55.928+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:55.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:57:56.012+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:56.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:56.173+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:57:56.159+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:57:56.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:57:56.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.680 seconds
[2024-02-22T00:58:39.238+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:58:40.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:58:40.301+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:58:40.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:58:44.450+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:58:44.104+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:58:44.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:58:47.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 11.566 seconds
[2024-02-22T00:59:07.876+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:07.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:59:08.064+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:59:08.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:09.038+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:59:08.911+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:59:09.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:10.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 2.555 seconds
[2024-02-22T00:59:13.295+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:13.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:59:13.400+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:59:13.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:13.964+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:59:13.866+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:59:13.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:14.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 1.666 seconds
[2024-02-22T00:59:47.832+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:47.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T00:59:48.058+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:59:48.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:49.464+0000] {logging_mixin.py:188} INFO - [2024-02-22T00:59:49.266+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T00:59:49.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T00:59:51.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 4.068 seconds
[2024-02-22T01:00:21.978+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T01:00:22.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T01:00:22.222+0000] {logging_mixin.py:188} INFO - [2024-02-22T01:00:22.201+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T01:00:22.789+0000] {logging_mixin.py:188} INFO - [2024-02-22T01:00:22.617+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T01:00:22.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T01:00:40.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 18.731 seconds
[2024-02-22T01:01:11.632+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/upload_docs.py
[2024-02-22T01:01:11.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_docs.py for tasks to queue
[2024-02-22T01:01:11.684+0000] {logging_mixin.py:188} INFO - [2024-02-22T01:01:11.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/upload_docs.py
[2024-02-22T01:01:11.833+0000] {logging_mixin.py:188} INFO - [2024-02-22T01:01:11.821+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/upload_docs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_docs.py", line 5, in <module>
    from airflow.contrib.sensors import GoogleCloudStorageObjectUpdatedSensor
ImportError: cannot import name 'GoogleCloudStorageObjectUpdatedSensor' from 'airflow.contrib.sensors' (/home/airflow/.local/lib/python3.8/site-packages/airflow/contrib/sensors/__init__.py)
[2024-02-22T01:01:11.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_docs.py
[2024-02-22T01:01:12.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_docs.py took 0.956 seconds
